### ISSUE TITLE
"Optimize" the interaction with Adroit.

### ISSUE THREAD

**Issue by shochdoerfer** [bitExpert/pathfinder#14]
See the discussion in the [Adroit issue tracker](https://github.com/bitExpert/adroit/issues/19). This will require a change in the Pathfinder repository as well.

**Comment by dropdevcoding** [comment]
I intentionally didn't implement more than target getter, params getter and a success flag, since I think there's no need to populate anything else outside routing. We could put in some more information though, but I don't think it should be necessary. What do you think?

Also I removed the tests for merging the route params with request params because this should be part of Adroit now (or any other implementation which is using Pathfinder).

**Comment by shochdoerfer** [comment]
Sounds good to me for the first version ;)
